# Generated by Django 4.1.5 on 2023-09-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pic',
            field=models.ImageField(default='media/forums/Dragonfruit2.jpg', upload_to='profiles'),
        ),
    ]
