# Generated by Django 4.1.5 on 2023-09-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pic',
            field=models.ImageField(default='/Dragonfruit.jpg', upload_to='profiles'),
        ),
    ]
